version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
      - /app/build
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
